Be app 0166
yes-soft-de/call-for-delivery pull request #193
Opened 2022-03-26 16:37 UTC by habibdevsy

- order logs

2022-03-26 17:43 UTC, ralsalloum approved these changes

2022-03-26 20:50 UTC, Kenan-Hussein commented on backend/src/Entity/OrderLogsEntity.php
> +class OrderLogsEntity
order status is missing

2022-03-26 20:50 UTC, Kenan-Hussein requested changes
Request changes

2022-03-26 21:31 UTC, Kenan-Hussein commented on backend/src/Entity/CaptainEntity.php
> +        if (!$this->OrderLogsEntity->contains($orderLogsEntity)) {
to make PHP stan happy please add space after "!"

2022-03-26 21:33 UTC, Kenan-Hussein commented on backend/src/Entity/OrderLogsEntity.php
> +    private $captainProfile;
if this not null, how you will be able to insert the first status of order: "order created" ?

2022-03-26 21:34 UTC, Kenan-Hussein commented on backend/src/Entity/OrderLogsEntity.php
> +class OrderLogsEntity
let us add branch Id also, will be much use of data

2022-03-26 21:42 UTC, Kenan-Hussein commented on backend/src/Manager/Order/OrderManager.php
>  class OrderManager
Ehm Ehm:
please move this logic "create logs" to its own service.
then call it from order service.
this approach kills the "single responsibility" principle

2022-03-26 21:45 UTC, Kenan-Hussein commented on backend/src/Manager/OrderLogs/OrderLogsManager.php
> +    public function create(OrderLogsCreateRequest $request): ?OrderLogsEntity
what is the use case of htis? please message me for this topic

2022-03-28 14:38 UTC, ralsalloum commented on backend/src/Request/OrderLogs/OrderLogsCreateRequest.php
> +   private null|StoreOwnerBranchEntity $storeOwnerBranch;
Why store branch may have null type while it is for sure there will be a branch to request an order from?

2022-03-28 14:40 UTC, ralsalloum commented on backend/src/Request/OrderLogs/OrderLogsCreateRequest.php
> +   public function getOrderId()
LOL, functions' return types are missing :)

2022-03-28 14:42 UTC, ralsalloum commented on backend/src/Request/OrderLogs/OrderLogsCreateRequest.php
> +namespace App\Request\Rate;
DANGER: namespace path is not correct.

2022-03-28 14:43 UTC, ralsalloum commented on backend/src/Manager/OrderLogs/OrderLogsManager.php
> +        $this->orderLogsEntityRepository = $orderLogsEntityRepository;
orderLogsEntityRepository variable is not defined.

2022-03-28 14:44 UTC, ralsalloum commented on backend/src/Manager/Order/StoreOrderDetailsManager.php
> +    public function getOrderDetailsByOrderId($orderId): StoreOrderDetailsEntity
type hint is missing.

2022-03-28 14:45 UTC, ralsalloum commented on backend/src/Manager/Order/StoreOrderDetailsManager.php
> +        $this->storeOrderDetailsEntityRepository = $storeOrderDetailsEntityRepository;
storeOrderDetailsEntityRepository variable is not defined :)

2022-03-28 14:49 UTC, ralsalloum commented on backend/src/Service/OrderLogs/OrderLogsService.php
> +    public function createOrderLogsRequest(OrderEntity $order): ?OrderLogsResponse
How could function return null as long as it returns the response of _createOrderLogs_ functions, which is **OrderLogsResponse** only?

2022-03-28 14:52 UTC, ralsalloum requested changes
Please check the new notes. Besides, how about adding an API to get order logs?

2022-03-28 15:22 UTC, ralsalloum approved these changes

2022-03-29 08:42 UTC, Kenan-Hussein approved these changes

2022-03-29 08:42 UTC, merged