Be admin 0200
yes-soft-de/call-for-delivery pull request #235
Opened 2022-04-06 14:28 UTC by habibdevsy

- Captain Financial System entities
- Captain Financial System (get for captain)

2022-04-06 14:55 UTC, ralsalloum commented on backend/src/Controller/Admin/CaptainFinancialSystem/AdminCaptainFinancialSystemAccordingOnOrderController.php
> +     *          @OA\Property(type="integer", property="categoryName"),
categoryName is of type string.

2022-04-06 14:58 UTC, ralsalloum commented on backend/src/Controller/Admin/CaptainFinancialSystem/AdminCaptainFinancialSystemAccordingOnOrderController.php
> +        $violations = $this->validator->validate($request);
FYI: there is no validator for AdminCaptainFinancialSystemAccordingOnOrderCreateRequest in the validation file.

2022-04-06 15:14 UTC, ralsalloum commented on backend/src/Request/Admin/CaptainFinancialSystem/AdminCaptainFinancialSystemAccordingToCountOfHoursCreateRequest.php
> +}
New empty line at the end of the file is needed.

2022-04-06 15:21 UTC, ralsalloum commented on backend/src/Controller/Admin/CaptainFinancialSystem/AdminCaptainFinancialSystemAccordingToCountOfHoursController.php
> +     *      description="Returns payments",
description field needs to be updated.

2022-04-06 15:33 UTC, ralsalloum commented on backend/src/Controller/Admin/CaptainFinancialSystem/AdminCaptainFinancialSystemAccordingToCountOfOrdersController.php
> +     *      description="Returns Captain's Financial System According On Order",
description field must be updated to: ... According on count of orders (not orders), right? :)

2022-04-06 15:44 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingOnOrderController.php
> +    private CaptainFinancialSystemAccordingOnOrderService $CaptainFinancialSystemAccordingOnOrderService;
variable name must start with small letter.

2022-04-06 15:46 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingOnOrderController.php
> +        $this->CaptainFinancialSystemAccordingOnOrderService = $CaptainFinancialSystemAccordingOnOrderService;
Please correct the var name here and in the function definition.

2022-04-06 15:48 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingOnOrderController.php
> +     *      description="Returns payments",
description field needs to be changed.

2022-04-06 15:52 UTC, ralsalloum commented on backend/src/Service/CaptainFinancialSystem/CaptainFinancialSystemAccordingOnOrderService.php
> +    private CaptainFinancialSystemAccordingOnOrderManager $CaptainFinancialSystemAccordingOnOrderManager;
Variable name must be small letter. And check all places in which it is being used.

2022-04-06 15:54 UTC, ralsalloum commented on backend/src/Response/CaptainFinancialSystem/CaptainFinancialSystemAccordingOnOrderResponse.php
> +}
New empty line at the end of the file is needed.

2022-04-06 16:02 UTC, ralsalloum commented on backend/src/Manager/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfHoursManager.php
> +        $this->entityManager = $entityManager;
entityManager variable is not defined.

2022-04-06 16:04 UTC, ralsalloum commented on backend/src/Service/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfHoursService.php
> +    private CaptainFinancialSystemAccordingToCountOfHoursManager $CaptainFinancialSystemAccordingToCountOfHoursManager;
Please update the variable name, and check all places in which it is being used.

2022-04-06 16:05 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfHoursController.php
> + * Create and fetch Captain's Financial System According To Count Of Hours.
route description needs to be updated (there is no create APIs here).

2022-04-06 16:06 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfHoursController.php
> +    private CaptainFinancialSystemAccordingToCountOfHoursService $CaptainFinancialSystemAccordingToCountOfHoursService;
Change the variable name (can not start with capital letter), and check all places in which it is being used.

2022-04-06 16:08 UTC, ralsalloum commented on backend/src/Service/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfOrdersService.php
> +    private CaptainFinancialSystemAccordingToCountOfOrdersManager $CaptainFinancialSystemAccordingToCountOfOrdersManager;
Alter the first letter of the var name from capital to small letter, and check all places in which it is being used.

2022-04-06 16:09 UTC, ralsalloum commented on backend/src/Response/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfOrdersResponse.php
> +}
Add new empty line at the end of the file please.

2022-04-06 16:10 UTC, ralsalloum commented on backend/src/Manager/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfOrdersManager.php
> +        $this->entityManager = $entityManager;
entityManager is being used but not defined.

2022-04-06 16:11 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfOrdersController.php
> +    private CaptainFinancialSystemAccordingToCountOfOrdersService $CaptainFinancialSystemAccordingToCountOfOrdersService;
update the var name (can not start with capital letter), and change it also in all places in which it is being used.

2022-04-06 16:12 UTC, ralsalloum commented on backend/src/Controller/CaptainFinancialSystem/CaptainFinancialSystemAccordingToCountOfOrdersController.php
> + * @Route("v1/captainfinancialsystemaccordingntocountoforders/")
mmm there is no create APIs here. Please update the route description.

2022-04-06 16:13 UTC, ralsalloum requested changes, later dismissed
Please resolve the requested changes.

2022-04-07 09:11 UTC, Kenan-Hussein approved these changes

2022-04-07 09:14 UTC, merged