refactor for the return type and necessary things
yes-soft-de/call-for-delivery pull request #68
Opened 2022-03-05 15:03 UTC by habibdevsy

- refactor for the return type and necessary things

2022-03-05 19:01 UTC, ralsalloum commented on backend/src/Controller/Subscription/SubscriptionController.php
> +    private $validator;
Class parameters' types need to be declared.

2022-03-05 19:01 UTC, ralsalloum commented on backend/src/Manager/Subscription/SubscriptionManager.php
> +    private $subscribeRepository;
Class parameters' types need to be declared.

2022-03-05 19:05 UTC, ralsalloum commented on backend/src/Service/Subscription/SubscriptionService.php
> +    private $subscriptionManager;
Class parameters' types need to be declared.

2022-03-05 19:06 UTC, ralsalloum commented on backend/src/Service/Subscription/SubscriptionService.php
> +    public function getIsFutureState(int $storeOwner): INT
Why INT not int?

2022-03-05 19:08 UTC, ralsalloum requested changes
Please resolve the request changes.

2022-03-06 05:13 UTC, habibdevsy commented
- resolve the requested changes is done.

2022-03-06 17:13 UTC, ralsalloum approved these changes

2022-03-06 19:14 UTC, merged