Refactored be st 0039
yes-soft-de/call-for-delivery pull request #91
Opened 2022-03-08 20:15 UTC by ralsalloum

- profilecompleteaccountstatus of type GET API was added.
- profilecompleteaccountstatus of type PUT was added.

2022-03-08 20:20 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     * store, captain, and supplies: Get complete account status of the user.
main controller must not have this APIs please move this endpoints to new controller

2022-03-08 20:22 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     * store, captain, and supplies: Get complete account status of the user.
also same for main service

2022-03-08 20:23 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     *          @OA\Property(type="string", property="status_code", example="9158 | 9159 | 9160 | 9161 | 9004"),
this example is confusing

2022-03-08 20:23 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     *
is granted  is missing

2022-03-08 20:24 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     * store, captain, and supplies: Update complete account status of the user.
is granted is missing

2022-03-08 20:25 UTC, Kenan-Hussein commented on backend/src/Controller/Main/MainController.php
> +     * store, captain, and supplies: Update complete account status of the user.
and we will use with each normal role a stable role called ROLE_USER 
to let all user types use this api and the other one and so the new apis

2022-03-08 20:26 UTC, Kenan-Hussein requested changes
Request changes

2022-03-08 22:46 UTC, Kenan-Hussein commented on backend/src/Controller/Account/AccountController.php
> +     * @IsGranted("ROLE_USER")
how this will work if we do not have this role in DB?

2022-03-08 22:46 UTC, Kenan-Hussein commented on backend/src/Controller/Account/AccountController.php
> +     * @IsGranted("ROLE_USER")
did this work localy?!

2022-03-08 22:47 UTC, Kenan-Hussein requested changes
changes requested

2022-03-08 22:50 UTC, ralsalloum commented on backend/src/Controller/Account/AccountController.php
> +     * @IsGranted("ROLE_USER")
Yes, it did.

2022-03-09 16:04 UTC, Kenan-Hussein approved these changes

2022-03-09 17:13 UTC, merged