add image to order when create and get
yes-soft-de/call-for-delivery pull request #96
Opened 2022-03-09 17:44 UTC by habibdevsy

- add image to order when create and get

2022-03-09 20:38 UTC, ralsalloum commented on backend/src/Controller/Order/OrderController.php
> +     *                  @OA\Property(type="array", property="images",
We have to deal with the front for this response.

2022-03-09 20:40 UTC, ralsalloum commented on backend/src/Service/Order/OrderService.php
> +    public function createImage(string $image, $id): ?ImageCreateResponse
type hint for _id_ is missing.

2022-03-10 07:50 UTC, Kenan-Hussein commented on backend/src/Service/Order/OrderService.php
> +            $this->createImage($request->getImages(), $order->getId());
let us call this method only if there is really image

2022-03-10 07:54 UTC, Kenan-Hussein commented on backend/src/Service/Order/OrderService.php
> +        $order['images'] = $this->imageService->getImagesByItemIdAndEntityTypeAndImageAim($id, ImageEntityTypeConstant::ENTITY_TYPE_ORDER, ImageUseAsConstant::IMAGE_USE_AS_ORDER_IMAGE);
هذا سيتطلب كويري اضافية، الرجاء تعديل جدول الطلبات ليصبح حقل الصوة علاقة مع جدول الصور الجديد بالتال يتم الحصل عليهم تلقائياً.
ثم الاستعانة بالهيلبر لهندسة شكل ريسبونس الصور

2022-03-10 07:55 UTC, Kenan-Hussein commented on backend/src/Service/Order/OrderService.php
> +        $order['images'] = $this->imageService->getImagesByItemIdAndEntityTypeAndImageAim($id, ImageEntityTypeConstant::ENTITY_TYPE_ORDER, ImageUseAsConstant::IMAGE_USE_AS_ORDER_IMAGE);
@habibdevsy @ralsalloum

2022-03-10 08:04 UTC, Kenan-Hussein requested changes
changes requested

2022-03-13 16:27 UTC, ralsalloum approved these changes

2022-03-14 22:10 UTC, Kenan-Hussein approved these changes

2022-03-14 22:39 UTC, merged